### ISSUE TITLE
Reference Error while starting new grommet app

### ISSUE THREAD

**Issue by gaswath** [grommet/grommet-cli#3]
Reference error is output when        grommet new (App name) is entered.

C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\bin\utils\cli.js:77
    console.error('[' + grommetDelimiter + '] Grommet requires Node v' + supportedNodeVersion + '+ and NPM v' + supportedNpmVersion + '+.');
                        ^

ReferenceError: grommetDelimiter is not defined
    at dependenciesSupported (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\bin\utils\cli.js:77:25)
    at CommandInstance.<anonymous> (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\bin\commands\new.js:29:41)
    at EventEmitter.session.execCommandSet (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\node_modules\vorpal\dist\session.js:473:20)
    at EventEmitter.vorpal._exec (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\node_modules\vorpal\dist\vorpal.js:975:18)
    at EventEmitter.vorpal._execQueueItem (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\node_modules\vorpal\dist\vorpal.js:766:17)
    at EventEmitter.vorpal._queueHandler (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\node_modules\vorpal\dist\vorpal.js:750:10)
    at EventEmitter.vorpal.exec (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\node_modules\vorpal\dist\vorpal.js:697:10)
    at EventEmitter.Vorpal.parse (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\node_modules\vorpal\dist\vorpal.js:172:12)
    at Object.<anonymous> (C:\Users\userName\AppData\Roaming\npm\node_modules\grommet-cli\bin\grommet.js:37:7)
    at Module._compile (module.js:409:26)

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-cli/commit/31c5092fd7d97c0324105cfbdd0e5dc210e1c5d4

I guess you have also an outdated version of Node or NPM.

0.1.5 released with the fix for the undefined variable.

Thanks for reporting.
